name: Automatisation GDR Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Créer une branche de mise à jour
        run: |
          UPDATE_BRANCH=update-auto-$(date +%s)
          echo "UPDATE_BRANCH=$UPDATE_BRANCH" >> $GITHUB_ENV
          git checkout -b $UPDATE_BRANCH

      - name: Vérifier si des modifications sont nécessaires
        run: |
          if git diff --quiet .github/workflows/main.yml; then
            echo "Aucune modification nécessaire, arrêt du workflow."
            exit 0
          else
            echo "# Mise à jour automatique" >> .github/workflows/main.yml
          fi

      - name: Vérifier les modifications avant commit
        run: |
          if git diff --quiet; then
            echo "Aucune modification détectée, arrêt du workflow."
            exit 0
          fi

      - name: Configurer Git
        run: |
          git config --global user.name "GDR Bot"
          git config --global user.email "gdr-bot@example.com"

      - name: Commit et push des modifications
        run: |
          git add .github/workflows/main.yml
          git commit -m "Mise à jour automatique du fichier main.yml"
          git push --set-upstream origin ${{ env.UPDATE_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Créer une Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.UPDATE_BRANCH }}
          title: "Mise à jour automatique du fichier main.yml"
          body: "Cette pull request a été créée automatiquement par le workflow GDR."
